Adding header row management
Zhouzi/react-sheets-import pull request #1
Opened 2018-09-19 15:35 UTC by Ctrl-X

I've added a checkbox to exclude by default the header column while still been able to use it in the column mapping.

+ Small typo fix on "mapPropsToRows" -> change to "mapColumnsToRows"

2018-09-23 20:20 UTC, zhouzi requested changes
Thanks so much, boss! :muscle: That's definitely a nice addition. I believe there are a few styling issues, you can fix them by running `yarn run lint --fix`.

2018-09-23 20:20 UTC, zhouzi commented on examples/Examples.js
> +            rows.shift();
`rows.shift()` mutates the original array so it's actually removing the first row from the state. An elegant and non-mutable alternative could be:

```javascript
const rows = isIgnoreHeaderRow ? this.state.rows.slice(1) : this.state.rows;
```

2018-09-23 20:20 UTC, zhouzi commented on examples/Examples.js
> +                                onChange={ () => this.setState({isIgnoreHeaderRow:!isIgnoreHeaderRow})}
`this.setState` is asynchronous so it's usually better to use [a function](https://reactjs.org/docs/react-component.html#setstate) when updating the state requires reading from it. You could add a method on the component like so:

```javascript
onToggleIgnoreHeaderRow = () => {
  this.setState(({ isIgnoreHeaderRow }) => ({
    isIgnoreHeaderRow: !isIgnoreHeaderRow
  }));
};
```

2018-09-23 20:20 UTC, zhouzi commented on src/parsers/xlsx.js
> +                const rows = XLSX.utils.sheet_to_json(sheet, {header:1, blankrows:false, defval:null});
I believe this is already being taken care of in the component. If not, it should be passed as an option and implemented in both of the parsers (CSV and XLSX). But I'd prefer not to add an option if it doesn't have any particular advantage over letting the user slice the array as he pleases.

2018-09-26 15:33 UTC, Ctrl-X commented
No prob, I've changed the portion you mentioned

2018-09-26 15:50 UTC, Ctrl-X commented on src/parsers/xlsx.js
> +                const rows = XLSX.utils.sheet_to_json(sheet, {header:1, blankrows:false, defval:null});
Well, for the header:1, the default behavior of XLSX.utils() is to ignore the header whereas the Papa CSV lib is using it by default. So it's more consistent to always keep it, and let the UI layer be in charge of removing/keeping the header.

2018-09-26 15:56 UTC, Ctrl-X commented on examples/Examples.js
> +            rows.shift();
Nicely put !

2018-09-26 15:56 UTC, Ctrl-X commented on examples/Examples.js
> +                                onChange={ () => this.setState({isIgnoreHeaderRow:!isIgnoreHeaderRow})}
Changed

2018-09-26 15:57 UTC, Ctrl-X commented on src/parsers/xlsx.js
> +                const rows = XLSX.utils.sheet_to_json(sheet, {header:1, blankrows:false, defval:null});
And for defval:null, it seems that rows that contain some empty cells are shifting cells to the left if 'defval' not specified

2018-09-26 23:31 UTC, Ctrl-X commented
Also not related to header management, but related to the changes made on null
 I've added a fix for Types : Now if a value is null, it won't be converted in String("null") or Boolean(false). It will stay null in the JSON result

2018-09-27 07:49 UTC, zhouzi approved these changes
Awesome, thanks! 😊

2018-09-27 07:49 UTC, merged